/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IWETH9,
  IWETH9Interface,
} from "../../../../contracts/handlers/weth/IWETH9";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IWETH9__factory {
  static readonly abi = _abi;
  static createInterface(): IWETH9Interface {
    return new utils.Interface(_abi) as IWETH9Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IWETH9 {
    return new Contract(address, _abi, signerOrProvider) as IWETH9;
  }
}
