/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDSProxy } from "./IDSProxy";
export type { IDSProxyFactory } from "./IDSProxyFactory";
export type { IDSProxyRegistry } from "./IDSProxyRegistry";
