/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ixProxySol from "./IxProxy.sol";
export { IDSA__factory } from "./IDSA__factory";
export { IERC20Usdt__factory } from "./IERC20Usdt__factory";
export { IInstaEngine__factory } from "./IInstaEngine__factory";
export { IInstaIndex__factory } from "./IInstaIndex__factory";
export { ITokenBridge__factory } from "./ITokenBridge__factory";
export { IWormhole__factory } from "./IWormhole__factory";
export { IxEngine__factory } from "./IxEngine__factory";
export { IxHolas__factory } from "./IxHolas__factory";
