/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDSProxy__factory } from "./IDSProxy__factory";
export { IDSProxyFactory__factory } from "./IDSProxyFactory__factory";
export { IDSProxyRegistry__factory } from "./IDSProxyRegistry__factory";
