/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as ixProxySol from "./IxProxy.sol";

export type { ixProxySol };
export type { IDSA } from "./IDSA";
export type { IERC20Usdt } from "./IERC20Usdt";
export type { IInstaEngine } from "./IInstaEngine";
export type { IInstaIndex } from "./IInstaIndex";
export type { ITokenBridge } from "./ITokenBridge";
export type { IWormhole } from "./IWormhole";
export type { IxEngine } from "./IxEngine";
export type { IxHolas } from "./IxHolas";
