/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { PromiseOrValue } from "../../../../../../common";
import type {
  DSGuardEvents,
  DSGuardEventsInterface,
} from "../../../../../../contracts/handlers/maker/dapphub/DSGuard.sol/DSGuardEvents";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "src",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "dst",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "sig",
        type: "bytes32",
      },
    ],
    name: "LogForbid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "src",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "dst",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "sig",
        type: "bytes32",
      },
    ],
    name: "LogPermit",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50601680601d6000396000f3fe6080604052600080fdfea164736f6c634300080a000a";

type DSGuardEventsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DSGuardEventsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DSGuardEvents__factory extends ContractFactory {
  constructor(...args: DSGuardEventsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<DSGuardEvents> {
    return super.deploy(overrides || {}) as Promise<DSGuardEvents>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): DSGuardEvents {
    return super.attach(address) as DSGuardEvents;
  }
  override connect(signer: Signer): DSGuardEvents__factory {
    return super.connect(signer) as DSGuardEvents__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DSGuardEventsInterface {
    return new utils.Interface(_abi) as DSGuardEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DSGuardEvents {
    return new Contract(address, _abi, signerOrProvider) as DSGuardEvents;
  }
}
